# backend:
#   name: test-repo
#   # branch: version2 # Branch to update (optional; defaults to master)

# media_folder: static/img
# public_folder: /img

# collections:
#   - name: "blog"
#     label: "Blog"
#     folder: "content/blog"
#     create: true
#     slug: "index"
#     media_folder: ""
#     public_folder: ""
#     path: "{{title}}/index"
#     editor:
#       preview: true
#     fields:
#       - { label: "Title", name: "title", widget: "string" }
#       - { label: "Publish Date", name: "date", widget: "datetime" }
#       - { label: "Description", name: "description", widget: "string" }
#       - { label: "Body", name: "body", widget: "markdown" }

backend:
  name: github
  repo: Karan0009/my-website
  branch: version2

media_folder: static/assets
public_folder: assets

# collections:
#   - name: blog
#     label: Blog
#     folder: content/blog
#     create: true
#     fields:
#       - { name: path, label: Path }
#       - { name: date, label: Date, widget: datetime }
#       - { name: title, label: Title }
#       - { name: body, label: Body, widget: markdown }
#       - {
#           name: featuredImage,
#           label: Thumbnail,
#           widge: image,
#           choose_url: true,
#           default: "../assets/default__ohlala.jpg",
#         }

collections:
  - name: "blog"
    label: "Blogs"
    folder: "content/blog"
    create: true
    fields:
      - { name: title, label: Title, required: true, widget: string }
      - { name: isActive, label: isActive, required: true, widget: boolean }
      - { name: slug, label: Slug, widget: string, required: true }
      - {
          name: publishedDate,
          label: "Published date",
          widget: datetime,
          required: true,
        }
      - {
          name: updatedDate,
          label: "Update date",
          widget: datetime,
          required: true,
        }
      - {
          name: featuredImage,
          label: Thumbnail,
          widge: image,
          choose_url: true,
          default: "/assets/default__ohlala.jpg",
        }
      - { name: body, label: Body, widget: markdown, required: true }
  - name: "projects"
    label: "Projects"
    folder: "content/projects"
    create: true
    fields:
      - { name: "title", label: "Title", required: true, widget: string }
      - { name: "isActive", label: "isActive", required: true, widget: boolean }
      - { name: slug, label: Slug, widget: string, required: true }
      - {
          name: startDate,
          label: "Start date",
          widget: datetime,
          required: true,
        }
      - { name: endDate, label: "End date", widget: datetime, required: true }
      - {
          name: featuredImage,
          label: Thumbnail,
          widge: image,
          choose_url: true,
          default: "/assets/default__ohlala.jpg",
        }
      - { name: "codeUrl", label: "Code url", required: false, widget: string }
      - { name: "demoUrl", label: "Demo url", required: false, widget: string }
